GET http://localhost:3006/api/users

###
POST http://localhost:3006/api/todos
Content-Type: application/json


{
    "text": "First Task"
}

###
PUT http://localhost:3006/api/goals/11

###
DELETE  http://localhost:3006/api/goals/11212121212